### ISSUE TITLE
Is there anyway to do this without environment variables?

### ISSUE THREAD

**Issue by AskYous** [googleapis/nodejs-billing#125]
I plan to use this library in firebase functions. And the [authentication process](https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable) doesn't give an option except to use environment variables.

Can I just hard-code some credentials into the code? Or hard-code the location of the json files for the service account?

Not sure how I would set an environment variable with the location of the json file in firebase functions.

**Comment by sofisl** [comment]
HI @AskYous, you can read more about the different authentication strategies [here](https://cloud.google.com/docs/authentication) to pick the best one for your needs. 

If you want to use a service account with firebase functions, you can set them in your [environment configuration](https://firebase.google.com/docs/functions/config-env). You can also maybe store it in a bucket or using secret manager, and then have the function grab it from either of these places. 

If you have any further questions, feel free to include them [here](https://github.com/googleapis/google-auth-library-nodejs), with some more details on your environment/what you're looking to accomplish.

Thanks!
