### ISSUE TITLE
Generate monthly cost report

### ISSUE THREAD

**Issue by yfried** [googleapis/nodejs-billing#99]
Hi,
I'm trying to use this tool to [get the same cost-table available in console](https://cloud.google.com/billing/docs/how-to/pricing-table#download-to-csv) but I'm stuck once I get to the SKU level.

How can I get the monthly cost from that?

```javascript
    const [accounts] = await client.listBillingAccounts({
        
    });
    for (const account of accounts) {
        console.info(`${account.name}: ${account.displayName}:`);
        const [projects] = await client.listProjectBillingInfo({name: account.name})
        
        for (const project of projects) {
            const catalogClient = new CloudCatalogClient({projectId: project.projectId});
            const [services, nextPageToken] = await catalogClient.listServices({});
            for (const service of services) {
                const [skus] = await catalogClient.listSkus({
                    parent: service.name,
                    startTime: {seconds: Math.round(+(Date.UTC(year, month, 1)) / 1000), nanos: 0},
                    endTime: {seconds: Math.round(+(Date.UTC(year, month + 1, 0)) / 1000), nanos: 0}
                })
                console.table(skus)
            }

        }
        console.table(projects)
    }
```

How can I modify this script to aggregate the monthly costs for each project (I don't care about the internal service/sku breakdown)?

**Comment by francesco-clementi-92** [comment]
If it's a solution for you I'm using the feature "export billing data to bigquery" to get the same cost table available on console.

Documentation: https://cloud.google.com/billing/docs/how-to/export-data-bigquery

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this is still a question for you, please feel free to reopen there! Thank you!
